### ISSUE TITLE
Radio button selection states bug

### ISSUE THREAD

**Issue by hristorv** [afollestad/material-dialogs#790] opened 2015-10-26 15:17 UTC
After you open a dialog with radio buttons, select one of the items, then rotate the device(change orientation) and select another radio button, the old one stays selected, so it looks like you have 2 radio buttons selected.

**Comment by afollestad** [comment] 2015-10-26 15:18
This is a duplicate of a few other issues.

Last time I checked, it was an issue specifically with Android 5.0.1 that couldn't really be fixed. It doesn't happen on 5.1 or 6.0.

**Comment by hristorv** [comment] 2015-10-26 15:39
This issue happens on Android 5.0.1 , 4.2 and 4.4 , i have tested it on real devices and that bug happens on all of them

**Comment by hristorv** [comment] 2015-10-27 13:32
For all Android versions there is a bug, when you rotate the device and select another radio button the previous one does not reset. In the MaterialDialog.class in the method onItemClick(), where you uncheck the previous item you need to add adapter.notifyDataSetChanged() after you use setChecked(false). That will fix the issue.
As for 5.0.1 issue, we can easiliy fix it with using       android:button="@drawable/abc_btn_radio_material"
In the radio button in md_listitem_singlechoice. This is hard coding the drawable, but this should not be a problem of any kind. I hope this helps anyone else who is trying to fix those issues.

**Closed** 2015-10-27 15:10 UTC
Labels: bug, compatibility issue
