### ISSUE TITLE
how to dismiss

### ISSUE THREAD

**Issue by tellfa** [afollestad/material-dialogs#745] opened 2015-10-08 11:01 UTC
i want use Progress Dialog , but i can't dismis this. 
please help me

my code :     m_dialog.title("بارگذاری")
                    .titleColorRes(R.color.accentColor)
                    .content("لطفا شکیبا باشید")
                    .contentColorRes(R.color.activity_bg_color)
                    .backgroundColorRes(R.color.dialog_color_black)
                    .progress(true, 0)
                    .show();

**Comment by afollestad** [comment] 2015-10-08 13:22
This is a duplicate of many other issues.

**Closed by afollestad** 2015-10-08 13:22 UTC

**Comment by afollestad** [comment] 2015-10-08 17:34
I added a new section to the README since so many cannot figure it out: [Dismissing Dialogs[(https://github.com/afollestad/material-dialogs#dismissing-dialogs)

**Comment by afollestad** [comment] 2015-10-08 17:34
I added a new section to the README since so many cannot figure it out: [Dismissing Dialogs](https://github.com/afollestad/material-dialogs#dismissing-dialogs)
