### ISSUE TITLE
Progress Dialog Spinner disappear (Android 4.3)

### ISSUE THREAD

**Issue by GarciaPL** [afollestad/material-dialogs#794] opened 2015-10-27 15:06 UTC
I am developing Android app which is compiled to SDK v. 23. I am also using ProGuard and I have added option to exclude ObjectAnimator from obfuscation. Your library works perfect, but I am not able to see spinner on Progress Dialog when I am running it on real device with Android 4.3. Weird thing is that on emulator (genymotion) it works. How can I fix this issue ? Of course I use your library as a AAR package.

**Comment by afollestad** [comment] 2015-10-27 15:08
This was fixed a few weeks ago with an update. Are you using 0.8.4.2?

Otherwise there's not much I can do, [MaterialProgressBar](https://github.com/DreaminginCodeZH/MaterialProgressBar) is being used and the Proguard rules required are already included in the AAR; you don't need any specific rules in your app, they get merged from the library.

**Comment by GarciaPL** [comment] 2015-10-27 15:44
Yes I am using the latest one, I mean 0.8.4.2. Maybe my Android 4.3 is not compatible for this ? I do not see also any strange stacktrace for progress dialog in logcat. I will check if this library MaterialProgressBar works on my device.

**Comment by afollestad** [comment] 2015-10-27 15:45
Being compatible with 4.0.4 and above is the reason why I switched to using that library, because it gets rid of bugs like this issue for me.

**Comment by afollestad** [comment] 2015-10-27 16:04
I should mention this is a duplicate of the following, and probably a few others:

https://github.com/afollestad/material-dialogs/issues/714
https://github.com/afollestad/material-dialogs/issues/708
https://github.com/afollestad/material-dialogs/issues/680
https://github.com/afollestad/material-dialogs/issues/667
https://github.com/afollestad/material-dialogs/issues/664
https://github.com/afollestad/material-dialogs/issues/636

**Closed** 2015-10-30 18:02 UTC
Labels: duplicate, possible bug
