### ISSUE TITLE
Incompatible with support library 23.2!

### ISSUE THREAD

**Issue by xxxifan** [afollestad/material-dialogs#961] opened 2016-02-25 02:38 UTC
With update support library to 23.2, error occurred while build:

    /home/xifan/StudioProjects/Feeling-Android-2nd/devbox/build/intermediates/exploded-aar/com.github.afollestad.material-dialogs/core/0.8.5.4/res/values-v11/values-v11.xml
    Error:(3, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

**Comment by afollestad** [comment] 2016-02-25 02:49
Duplicate of another issue, already fixed in the code.

**Closed by afollestad** 2016-02-25 02:49 UTC

**Comment by afollestad** [comment] 2016-02-25 05:00
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.5

**Comment by afollestad** [comment] 2016-02-25 05:07
The above won't work until JitPack installs version 23.2.0 of the Google libs repo.
