### ISSUE TITLE
Input dialog layout bug 

### ISSUE THREAD

**Issue by rupak0577** [afollestad/material-dialogs#1701] opened 2019-01-11 05:06 UTC
**Library Version:**

2.0.0-rc7
 
**Affected Device(s):**
 
All devices
 
**Describe the Bug:**

<img src="https://user-images.githubusercontent.com/10296115/51014161-34fb4d00-158c-11e9-8b90-56d86f031fe4.png" width="250" />

**Comment by afollestad** [comment] 2019-01-11 05:13
Duplicate of https://github.com/afollestad/material-dialogs/issues/1695

I haven't been able to reproduce.

**Comment by DeweyReed** [comment] 2019-01-16 10:38
I reproduced this bug when I upgraded materail version from 1.0.0 to `com.google.android.material:material:1.1.0-alpha02`.

**Comment by afollestad** [comment] 2019-01-16 19:54
That may be an alpha bug, then - I don't really do anything to modify the text input layout in this library's code

**Comment by sonhvp** [comment] 2019-01-17 04:02
It's a bug with material library, downgrade to "com.google.android.material:material:1.0.0" and it works like a charm.

**Closed** 2019-01-17 04:04 UTC
Labels: can't reproduce, duplicate
