### ISSUE TITLE
After Updating latest support design lib. in Eclipse

### ISSUE THREAD

**Issue by patelakshay13890** [afollestad/material-dialogs#973] opened 2016-02-26 07:44 UTC
After Updating latest support design lib. to 23.2 in Eclipse I am getting this error 
"
java.lang.NoSuchFieldError: No static field abc_ic_ab_back_mtrl_am_alpha of type I in class Landroid/support/v7/appcompat/R$drawable; or its superclasses (declaration of 'android.support.v7.appcompat.R$drawable'
"
SO what could be the solution ??
And I am using latest lib. of you

**Comment by RoadXY** [comment] 2016-02-26 11:56
Not limited to Eclipse: same happend when updating to 23.2 in Android Studio.

**Comment by RoadXY** [comment] 2016-02-26 12:34
Looks like it is solved in commit https://github.com/afollestad/material-dialogs/commit/5ceb034345adc8e8b0ed94852b2e84845694e09c

**Comment by patelakshay13890** [comment] 2016-02-26 14:33
I am getting still error after updating my Support Libs. in "ECLIPSE"..
SO what could be the solution ??

**Comment by afollestad** [comment] 2016-02-26 15:21
Duplicate of 6-7 closed issues.

**Comment by afollestad** [comment] 2016-02-26 15:21
Unrelated to Eclipse, which shouldn't be used anyways though.

**Closed by afollestad** 2016-02-26 15:21 UTC

**Comment by patelakshay13890** [comment] 2016-02-26 18:55
But how can I solve this problem in Eclipse , plz provide some solution

**Comment by afollestad** [comment] 2016-02-26 18:56
I don't have any solutions, Eclipse was deprecated by Google a long time ago and it should not be used.
