### ISSUE TITLE
Folder select dialog position error

### ISSUE THREAD

**Issue by spdv123** [afollestad/material-dialogs#1320] opened 2017-03-01 11:41 UTC
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of Material Dialogs.
- [x] I have given my issue a non-generic title.
- [x] I have read over the documentation (before asking questions on how to do something).

###### Include the following:
 - Material Dialogs version: `0.9.3.0`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Xiaomi`
 - Device Name: `Mi 5`

Also, please wrap Java with correct syntax highlighting.

```java
FolderChooserDialog.Builder folderChooserDialogBuilder = new FolderChooserDialog.Builder(this)
                .chooseButton(R.string.choose_path)  // changes label of the choose button
                .initialPath("/sdcard/Download")  // changes initial path, defaults to external storage directory
                .tag("optional-identifier")
                .goUpLabel(".."); // custom go up label, default label is "..."
```
 
###### Reproduction Steps

1.  Open a folder select dialog
2.  Select a folder
3.  It steps into the folder above the selected one

###### Expected Result

It steps into the selected folder

###### Actual Result

It steps into the folder above the selected one

**Comment by peterhav** [comment] 2017-03-03 21:40
Note: this is a duplicate of issue #1288 (which has been closed but not released). A fix is already committed: a new release would solve this issue.

**Closed** 2017-03-03 23:25 UTC
Labels: bug

**Comment by afollestad** [comment] 2017-03-08 19:27
https://github.com/afollestad/material-dialogs/releases/tag/0.9.4.0
