### ISSUE TITLE
question about edit text dialog

### ISSUE THREAD

**Issue by enricocid** [afollestad/material-dialogs#820] opened 2015-11-09 19:15 UTC
is it possible to add two edit text fields in input dialogs using a custom layout?
thanks:)

**Comment by afollestad** [comment] 2015-11-09 19:33
This is a possible duplicate of multiple issues.

Are you asking if you can add multiple edit text fields to a custom layout. Why wouldn't you be able to?

**Closed by afollestad** 2015-11-09 19:33 UTC
Labels: duplicate

**Comment by enricocid** [comment] 2015-12-05 10:42
Done, thank You:)

![senza nome](https://cloud.githubusercontent.com/assets/7274841/11607397/06581af6-9b45-11e5-9f11-5410efd14903.png)

**Comment by ebrirad** [comment] 2016-12-30 11:34
hey guy how you could solve this problem ... could you help me and write your code in here...

**Comment by enricocid** [comment] 2016-12-30 11:47
You Can see my implementation here

https://github.com/enricocid/iven-feed-reader

https://github.com/enricocid/iven-feed-reader/blob/master-as/project/app/src/main/res/layout/add_feed_layout.xml


addFeed() method in https://github.com/enricocid/iven-feed-reader/blob/master-as/project/app/src/main/java/com/iven/lfflfeedreader/mainact/ListActivity.java
