### ISSUE TITLE
Multiple EditText inputs in a Dialog

### ISSUE THREAD

**Issue by Berlon** [afollestad/material-dialogs#1114] opened 2016-06-29 18:33 UTC
Sorry to use the issue reporting method, but I was unable to find a email address to ask his question.

I like your library! and would like to use it in my application. However, I am unsure as of how to set multiple editText inputs and get those inputs to the activity on positive click. Can you help me?

**Comment by afollestad** [comment] 2016-06-29 18:41
Please follow the issue template for future issues.

This is a duplicate of multiple closed issues.

**Closed by afollestad** 2016-06-29 18:41 UTC

**Comment by Berlon** [comment] 2016-06-29 19:15
Maybe a link to the answer?

**Comment by afollestad** [comment] 2016-06-30 14:15
https://github.com/afollestad/material-dialogs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20multi%20line
