### ISSUE TITLE
Weird glitches when dialog changes size (redraws/remeasures)

### ISSUE THREAD

**Issue by afollestad** [afollestad/material-dialogs#272] opened 2015-02-23 18:27 UTC

**Comment by afollestad** [comment] 2015-02-23 18:28
@teslacoil that shake issue is still there.

I came across it while creating a FAQ dialog for Moonshine icon pack's redesigned dashboard (which I'm helping the dev out with).

It seems as though there's an infinite redraw loop going on here or something.

**Comment by afollestad** [comment] 2015-02-23 18:31
If it doesn't shake, then it seems to move up for a second, and then move down once measured.

**Comment by teslacoil** [comment] 2015-02-23 19:02
Do you have sample code to reproduce? (and the device/screen size/dpi you're testing against).

Just taking a quick look, 81197a67 seemed to add conditional titlebar padding, I'd guess that it needs similar constraints as the bottom margin in setDividerVisibility ("Only enable the bottom margin if our available window space can hold the margin")

The conditional padding is a pain. A custom root view that does the measures and applies the padding might be easier to maintain than having callbacks and checks in the Dialog, this might also help with the slow remeasure/relayouts as we should be able to do it in one pass, whereas it seem something is taking multiple passes here.

**Comment by afollestad** [comment] 2015-02-24 23:29
Well at the moment, it's noticeable with this library's sample project (the folder chooser).

It feels very laggy, and if the title divider appears for the first time it pushes the content down after 1-2 seconds.

**Comment by afollestad** [comment] 2015-02-24 23:30
I'm almost tempted to rebuild a lot of this library to use less programatic setup, but that would obviously take quite a bit of time.

**Comment by afollestad** [comment] 2015-02-25 00:13
@teslacoil actually, here's a good example. It's noticeable if you tap the "FAQ" option. When you tap to expand items in that dialog (more so when you do it a few times), the dialog lags and skips around: https://drive.google.com/file/d/0B3ztrEIRfGuCTDZEWEVlSHJkeUU/view?usp=sharing

**Comment by teslacoil** [comment] 2015-02-25 03:21
The shaking issue was showing the divider, triggering a relayout, and hiding the divider, so they wouldn't just wiggle once but continuously shake. (it didn't fully block the UI thread, but it was barely usable) This at least only happens once (per layout change).

The dividers could be simplified to be either VISIBLE or INVISIBLE, so they never cause layout changes, but the padding is killer, and the padding in the button bar changes the size of the content (which can change the size of the button bar, which we prevent, but I think still causes another measure/layout pass, and it changes the size of the window which might also cause a measure/layout pass).

There's also a user experience issue here, even without the lag, is it a good experience to have an on screen dialog change size? I'd say no. The FAQ example would be better if the first time you view the dialog it was full sized and clicking a question didn't change the window size/position. The folder chooser example would look a bit sparse when you're in an empty directory if the dialog didn't shrink back down, but personally I think the chooser is already bad UX for a number of reasons (file choosers in general though I admit there is a use at times, no clear way to know if back will cancel or go back, window drastically changes size, position of title and OK/Cancel move), so it might be better to ignore that use case and focus on ones like the FAQ.

I'm not personally using any dialogs that change size while on screen, so I don't have that strong of feelings on how they should work. Killing the button bar padding is kind of a shame for small dialogs, but it would simplify things. An option to force the divider/padding/scrollable mode regardless of content is kind of a workaround and awkward to name the parameter or document, but would be easy.

I can take a look at doing a custom root view that more intelligently handles the dividers and padding, preferably with just one pass (or at least one layout pass, maybe two measures). But it will likely need to wait until either I add require a dialog that changes size, or after I get my update released as stable.

**Comment by mattblang** [comment] 2015-03-04 17:02
@afollestad @teslacoil We noticed the issue when using [MaterialEditText](https://github.com/rengwuxian/MaterialEditText).  The `MaterialEditText` view typically does a resize animation when making room to display an error message.  When inside of a `MaterialDialog` the resize animation seems to happen, but the text doesn't appear until it is over.  [Here is a screen capture](https://www.youtube.com/watch?v=ODrQzP3cBpU&feature=youtu.be) showing the issue.

**Comment by andrewlord1990** [comment] 2015-03-07 09:57
I was getting glitches when using the sample Folder Chooser dialog and with my "fix" I believe it is not happening anymore.

The only problem, is I can't fix the glitch with hiding the 8dp margin below the buttons once the bottom divider is shown. It seems that when you set that margin to 0, it is actually applied later than the rest, so you see the buttons move down into place. The only way I could stop this was removing the 8dp bottom margin, but that made the normal dialog buttons look too close to the edge.

**Comment by afollestad** [comment] 2015-03-09 20:20
The recent pull request didn't fix this, it messed up some spacing in the process.

I undid it.

**Comment by andrewlord1990** [comment] 2015-03-09 20:27
Oh okay, fair enough. The Folder Chooser sample seemed to be much less glitchy, so thought it had improved it. Ah well!

**Comment by frmz** [comment] 2015-03-11 08:40
@andrewlord1990 can you issue a pull request to @afollestad ? that resizing bug its pretty annoying and i don't want to fork just for that since you already fixed it

**Comment by andrewlord1990** [comment] 2015-03-11 08:42
I'm really sorry. I did a pull request with my changes, as I observed the Folder Chooser sample was much more stable, but @afollestad has said that I didn't actually fix it, so it was reverted. Sorry.

**Comment by afollestad** [comment] 2015-03-28 00:33
It looks like the major issue now is that padding is invalidated in `onShow()` of `MaterialDialog.java`. There's a short delay from when the dialog actually shows, and when the OnShow callback is invoked by the Android framework.

**Comment by teslacoil** [comment] 2015-04-03 18:41
I've started on this, I created a custom MDRootLayout that does it's own measure/layout of the root elements (titlebar, content, buttons) and it can make the padding/stacking decisions all from onMeasure (so no need to invalidate after onShow). The folder chooser is so much faster and doesn't wiggle or draw at the wrong size momentarily or anything. I still need to verify the padding for various things as it's implemented a bit different now, but hopefully I can submit a pull request soon.

**Comment by afollestad** [comment] 2015-04-03 19:28
Awesome, sounds good. Whenever that's done, I will push another release along with the new progress dialog theming stuff.

**Comment by teslacoil** [comment] 2015-04-04 05:45
Here we go: https://github.com/afollestad/material-dialogs/pull/392

**Closed** 2015-04-04 06:18 UTC
Labels: bug, help wanted

**Comment by afollestad** [comment] 2015-04-06 23:39
https://github.com/afollestad/material-dialogs/releases/tag/v0.7.0.0
