### ISSUE TITLE
Artifact not on Maven (or jCenter).

### ISSUE THREAD

**Issue by pardom** [afollestad/material-dialogs#490] opened 2015-04-29 13:06 UTC
It appears the latest version has not been released to Maven. Additionally, older versions are no longer hosted either which has broken our CI builds.

**Comment by afollestad** [comment] 2015-04-29 13:31
This is a duplicate of many issues.

Also see the README.

**Closed by afollestad** 2015-04-29 13:31 UTC

**Comment by pardom** [comment] 2015-04-29 13:43
Thanks :+1:
