### ISSUE TITLE
'com.afollestad:material-dialogs:0.7.2.0' was unpublished

### ISSUE THREAD

**Issue by falkorichter** [afollestad/material-dialogs#489] opened 2015-04-28 13:52 UTC
'com.afollestad:material-dialogs:0.7.2.0' used to be deployed to jcenter, but now it is gone.

This breaks the reproduceablity of our builds!

**Comment by afollestad** [comment] 2015-04-28 13:57
This is a duplicate of many other issues

**Closed by afollestad** 2015-04-28 13:57 UTC

**Comment by falkorichter** [comment] 2015-04-28 14:04
It is still an issue. why do you need to unpublish the artifacts? It doesn´t harm anyone, if you just leave them. Or use the SNAPSHOT repository...

**Comment by afollestad** [comment] 2015-04-28 14:05
If you read the relevant issues you would know I didn't.

**Comment by afollestad** [comment] 2015-04-28 14:05
The library accidentally got removed from jCenter. It only recently went back up.

**Comment by falkorichter** [comment] 2015-04-28 14:08
Ah I see. So this did not happen on purpose.

At least paste a message that explains the situation.

Or leave one Issue open that explains, there was no open issue so I filed one.

You propably tried to publish the old versions?

**Comment by afollestad** [comment] 2015-04-28 14:09
I didn't try to publish old versions, I don't keep old versions around since users should always be using the latest version until version 1.0 is released. Anything less are beta builds and new versions tend to have important fixes or improvements.

**Comment by falkorichter** [comment] 2015-04-28 18:08
That´s the concept of -SNAPSHOT releases. You´re misusing the regular release feature.

**Comment by falkorichter** [comment] 2015-04-29 12:23
To quote bintray when you try to delete a version: "Are you sure you want to delete this version?
You already published this version '0.10.0RC17' and made it public.
People may have come to rely on your binaries and taking them away may impact trust and damage the reputation of your repository."

You can apply to publish Snapshots...

**Comment by afollestad** [comment] 2015-04-29 12:25
I didn't say a version was deleted, I said the entire repository was
deleted.

I don't plan on publishing snapshots though. One of the next few releases
will be version 1.0.
