### ISSUE TITLE
FileChooserDialog as a Preference

### ISSUE THREAD

**Issue by HashirLabs** [afollestad/material-dialogs#1077] opened 2016-05-17 10:50 UTC
What would be the best way to use FileChooserDialog as a preference dialog. I tried extending MaterialDialogPreference and overriding couple of methods including showDialog, but its kinda mess up, would like to hear from you if there is any better way than this.

**Comment by afollestad** [comment] 2016-05-17 15:53
This is a duplicate of a few older issues

**Closed by afollestad** 2016-05-17 15:53 UTC
