### ISSUE TITLE
Error after update library

### ISSUE THREAD

**Issue by balduzzi85** [afollestad/material-dialogs#430] opened 2015-04-09 16:01 UTC
Hi,

i have update the library with:

 compile 'com.afollestad:material-dialogs:0.7.1.0'

And i have this error:

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-7-oracle/bin/java'' finished with non-zero exit value 2

With previous version no problem..can you help?

my file gradle is:

apply plugin: 'com.android.application'

android {

    compileSdkVersion 22
    buildToolsVersion "22.0.1"
    defaultConfig {
        applicationId "package.com"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "Alpha 1"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    packagingOptions {
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE.txt'
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }

}

dependencies {
    //Core
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile files('libs/khandroid-httpclient-4.2.3.jar')
    compile files('libs/YouTubeAndroidPlayerApi.jar')
    compile files('libs/mpandroidchartlibrary-1-7-4.jar')
    compile files('libs/additionnal.jar')
    compile files('libs/mail.jar')
    compile files('libs/activation.jar')
    compile project(':library-viewpagerindicator')
    compile(name: 'com.doomonafireball.betterpickers', ext: 'aar') {
        exclude module: 'support-v4'
    }
    compile 'com.github.gabrielemariotti.cards:cardslib-core:2.0.1'
    compile 'com.github.gabrielemariotti.cards:cardslib-recyclerview:2.0.1'

    compile 'de.hdodenhof:circleimageview:1.2.1'
    compile 'com.mcxiaoke.volley:library:1.0.+'
    compile 'com.google.code.gson:gson:2.3.+'
    compile 'org.apache.commons:commons-lang3:3.3.2'
    compile 'com.amulyakhare:com.amulyakhare.textdrawable:1.0.1'
    compile 'com.jakewharton:butterknife:6.1.0'
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.android.support:support-v4:22.0.0'
    compile 'com.android.support:recyclerview-v7:21.0.3'
    compile 'com.afollestad:material-dialogs:0.7.1.0'
    compile 'com.makeramen:roundedimageview:2.0.0'
    compile 'joda-time:joda-time:2.1'
    compile 'de.greenrobot:eventbus:2.4.0'
    compile 'com.google.android.gms:play-services:6.5.87'
    compile 'org.osmdroid:osmdroid-android:4.3'
    compile 'org.slf4j:slf4j-simple:1.6.1'

}

**Comment by afollestad** [comment] 2015-04-09 16:23
This is a duplicate of 3 or 5 other issues if you were to do a search.

You need the jcenter() repository. Android Studio uses it by default but it looks like you override repositories.

**Closed by afollestad** 2015-04-09 16:23 UTC
Labels: duplicate

**Comment by hateum** [comment] 2015-04-09 16:29
You use many many libs.
I think because you have exceeded the limit of function used (65K).
Think to integrate MultiDex config to your gradle.

**Comment by balduzzi85** [comment] 2015-04-09 16:32
but previous the update it work... why now i need MultiDex ?

**Comment by hateum** [comment] 2015-04-09 17:47
I have the same Error like u and I resolve it by adding on the gradle:
dexOptions {
        jumboMode = true
    }

don't forget to clean your project after that.
