### ISSUE TITLE
Multiple EditText in Dialog Box

### ISSUE THREAD

**Issue by vijaykd** [afollestad/material-dialogs#1033] opened 2016-04-04 17:40 UTC
Great job in creating a library like this.. Solve major theme issues for dialog box.. Is it possible to have multiple EditText in a dialog box similar to this:
```
 new MaterialDialog.Builder(OZI_P_DetailActivity_new.this)
                        .title(getResources().getString(R.string.submitquery) + " for \n" + productCode)
                        .inputType(InputType.TYPE_CLASS_TEXT)
                        .theme(Theme.LIGHT)
                        .input(getResources().getString(R.string.firstname), null, new MaterialDialog.InputCallback() {
                            @Override
                            public void onInput(MaterialDialog dialog, CharSequence input) {
                                // Do something
                            }
                        }).show();
```

if so how?

**Comment by afollestad** [comment] 2016-04-04 17:41
This is a duplicate of many issues.

But no, you'll need a custom layout.

**Closed by afollestad** 2016-04-04 17:41 UTC
Labels: duplicate
