### ISSUE TITLE
Preference Items should be stylized as material

### ISSUE THREAD

**Issue by Fleker** [afollestad/material-dialogs#545] opened 2015-05-28 05:32 UTC
It's great that I can easily use `com.afollestad.materialdialogs.prefs.MaterialEditTextPreference` to display a preference that will open a material dialog with an EditText view and have it function great. However, when displayed in the preferences, the item still looks like a stock setting item on KitKat and lower.

What I would like to see is using that preference tag to emulate the style of https://github.com/jenzz/Android-MaterialPreference which is material, but not the advanced dialog preferences.

To make everything consistent now would be to use the other library and to set blank preferences that would open the dialog on a click. It would require a lot of custom code.

Using both libraries directly via XML make the preferences very streamlined, but end up with an inconsistent interface that is both material and holo on KK and lower.

**Comment by afollestad** [comment] 2015-05-28 13:01
Duplicate of an issue from yesterday.

**Closed by afollestad** 2015-05-28 13:01 UTC
