### ISSUE TITLE
MaterialDialog does not wrap content with custom view

### ISSUE THREAD

**Issue by odin-** [afollestad/material-dialogs#1282] opened 2017-02-04 09:04 UTC
- Material Dialogs version: `0.9.2.3`
 - API: `25`
 - Device Manufacturer: `Android`
 - Device Name: `Nexus 7` / `Android Emulator`

I invoke a MaterialDialog with my custom view:

```java
   new MaterialDialog.Builder(myActivity)
   .customView(view, false)
   .negativeText(R.string.dialog_user_profile_button)
   .title(user.getHandle())
   .show();
```

The problem is that the contents isn't wrapped, i.e. I the right margin is wider than the left. 

(This is a problem in AppCompat AlertDialog also).

**Comment by odin-** [comment] 2017-02-04 11:53
Seems to be a duplicate of #552

**Comment by afollestad** [comment] 2017-02-06 01:49
I would say it's more of a duplicate of https://github.com/afollestad/material-dialogs/issues/1264, but slightly different.

However, dialogs will look best if your custom views fill the width of the dialogs. I use the specs from the Material Design guidelines for the width of dialogs.

**Comment by odin-** [comment] 2017-02-06 08:40
Thanks for the input. I'll try to redesign the layout. Although it might be a not so good solution as I need to rework the content to the dialog, not sure it'll look great.

For AlertDialog I use AlertDialog.getWindow().setLayout to force the width. Can I do similar with MaterialDialog?

**Comment by PaulWoitaschek** [comment] 2017-05-12 20:16
I'd be happy if this gets implemented. I'm using a system component so I can't redesign the layout.

**Comment by AlejandroHCruz** [comment] 2017-07-25 14:54
I subscribe to this since I require a taller dialog than the standard one.

Being able to call something like this on the dialog might help, as @odin- said

`dialog.getWindow().setLayout(WindowManager.LayoutParams.MATCH_PARENT,WindowManager.LayoutParams.WRAP_CONTENT);`

**Comment by afollestad** [comment] 2018-08-15 04:46
Will no longer apply with upcoming version 2.0

**Closed by afollestad** 2018-08-15 04:46 UTC
Labels: enhancement, pre-version 2.0, version 2
