### ISSUE TITLE
Focus going to negative button when clicking on positive button

### ISSUE THREAD

**Issue by ViswanathL** [afollestad/material-dialogs#223] opened 2015-01-28 15:51 UTC
When you select positive button its focusing on negative button, leading to some bad UX.

**Comment by afollestad** [comment] 2015-01-28 21:34
Weird, nothing is done to explicitly change focus of buttons from my code. How often would that be an issue though? Generally a dialog should be dismissed when the positive action button is pressed.

**Comment by ViswanathL** [comment] 2015-01-29 04:15
Irrespective of dialog. As a button, it should not focus another when clicking on that right ?

**Comment by afollestad** [comment] 2015-01-29 04:16
It shouldn't, very weird that it does

**Comment by ViswanathL** [comment] 2015-01-29 04:21
MaterialDialog dialog = new MaterialDialog.Builder(this)
					.title("")
					.content("")
					.positiveText("Agree")
					.cancelable(false)
					.negativeText("Diasagree")
					.callback(new MaterialDialog.ButtonCallback() {
						@Override
						public void onPositive(MaterialDialog dialog) {
							// Code
						}

						@Override
						public void onNegative(MaterialDialog dialog) {
							// Code
						}
					}).build();
					dialog.show();


This is the code.

**Comment by afollestad** [comment] 2015-01-29 04:25
Yeah there's not much I can tell from that, unfortunately.

On a side note, you don't need to make a call to title() or content() if
they're empty. Neither is required. You also don't need to use build() and
then show() unless you use the MaterialDialog instance. You can immediately
call show() like a lot of the examples in the README and sample project do.

**Comment by ViswanathL** [comment] 2015-01-29 04:32
No problem. Please check and update me if you find the issue. i will try to find the same.

Thank you.

**Comment by afollestad** [comment] 2015-01-29 17:10
I have a feeling that is has something to do with the fact that I recently made the buttons focusable so that users with a physical keyboard can navigate them without a touch screen. Not sure why the focus would be changed automatically, though.

**Comment by afollestad** [comment] 2015-02-03 03:59
Just so you know, this is how you do syntax highlighting with markdown (not indents) ;) https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

But, I'm not able to find away to produce this currently.

**Comment by afollestad** [comment] 2015-02-03 04:45
I can't reproduce this so I'm closing it

**Closed by afollestad** 2015-02-03 04:45 UTC
Labels: bug
