### ISSUE TITLE
Using TextInputLayout.

### ISSUE THREAD

**Issue by hristorv** [afollestad/material-dialogs#786] opened 2015-10-24 10:38 UTC
I suggest adding TextInputLayout from the Design Library to the layout file md_dialog_input. I am currently using  it and it works great. Just add this code: 
 <android.support.design.widget.TextInputLayout
                android:id="@+id/text_input_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" >
The layout should wrap EditText layout.

**Comment by afollestad** [comment] 2015-10-24 14:58
This is a duplicate of another issue. It's not included because additional library dependencies like the Design Support Library are forced on apps that use Material Dialogs, thus increasing the size of the library and other apps.

**Closed by afollestad** 2015-10-24 14:58 UTC
Labels: duplicate
