### ISSUE TITLE
Multiple Input Fields

### ISSUE THREAD

**Issue by brunolopes446** [afollestad/material-dialogs#959] opened 2016-02-24 15:57 UTC
Hi.

Is it possible to have multiple input fields?
Like one asking for a username and another asking for a password, on the same dialog.
I already defined two inputs in the Builder but just the last one shows up.

Thank you

**Comment by afollestad** [comment] 2016-02-24 17:11
This is a duplicate of about a dozen issues.

---

But no, you'll need a custom view.

**Closed** 2016-02-24 17:11 UTC
Labels: duplicate, question, wontfix
