### ISSUE TITLE
Indeterminate progress doesn't work correctly on older API versions

### ISSUE THREAD

**Issue by AshkanImmortal** [afollestad/material-dialogs#636] opened 2015-07-29 13:19 UTC
in api 16 new horizontal indeterminate dialog doesn't show the progress bar, just title and content are visible.

**Comment by javaguy44** [comment] 2015-08-08 08:34
I've confirmed this bug.  
 - I've confirmed myself physically via a Galaxy S2 API 16.  
 - Also a user sent me a screenshot where this failed on a Galaxy S4 mini API 19 (which prompted my investigation)

I've narrowed it down, but after spending the last few hours through the source, I have to move on.  Hope what I've found helps:

1.  using the default layout md_dialog_progress_indeterminate_horizontal in a custom view works (make sure you pass false to wrap w/in scroll view).  Snippet:

                MaterialDialog dialog = new MaterialDialog.Builder(v.getContext())
                        .customView(R.layout.md_dialog_progress_indeterminate_horizontal, false)
                        .build();

                dialog.show();

2.  I modified md_stub_progress_indeterminate_horizontal, and changed ProgressBar so that  minHeight was 20dp and layout_height was 20dp.  This did not solve the issue.  It appears that MDRootLayout is not respecting those heights; or the content height is not correct

3.  I also modified MDRootLayout of md_dialog_progress_indeterminate_horizontal to have a layout_height of 200dp, and this didn't work either.


I can't say if it is Ssung specific, but certainly could be the case.  Indeterminate horizontal works fine on the following:
 - N7, N6, Moto G 2nd gen all running Lollipop 21 and 22

I also found this which might help:
https://github.com/DreaminginCodeZH/MaterialProgressBar/issues/1

My workaround for now is to use a MD customView with the DreaminginCodeZ/MaterialProgressBar library...which of course is not nice, but unfortunately I'm in a sprint and don't have the time -- mainly needed a workaround for the end user complaint.

Thanks and let me know if I can run anything else.

**Comment by afollestad** [comment] 2015-09-08 01:54
@javaguy44

**Comment by afollestad** [comment] 2015-09-08 01:54
Sorry for the delay.

Thanks for the library @javaguy44, since that library is relatively light weight, I think I'll be integrating it into the library. It's definitely a good solution for backwards compatibility.

**Comment by afollestad** [comment] 2015-09-08 02:16
Actually, nevermind, that library only supports API 14 and above.

**Comment by afollestad** [comment] 2015-09-12 21:15
Should be fixed for Android 4.0+ in the upcoming release.

**Closed by afollestad** 2015-09-12 21:15 UTC
Labels: bug, help wanted

**Comment by afollestad** [comment] 2015-09-17 20:36
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0

**Comment by javaguy44** [comment] 2015-09-19 07:22
Great stuff.  Sorry I couldn't be of more help, but glad that library helped.

Best and thanks for an awesome libray

**Comment by DreaminginCodeZH** [comment] 2015-09-23 07:13
Hi, I'm the author of [MaterialProgressBar](https://github.com/DreaminginCodeZH/MaterialProgressBar), and I'm glad that my library helped.

I've just updated my library this afternoon to provide a simple widget `MaterialProgressBar` which saves the boilerplate java code for setting the progress drawable, please feel free to integrate it.

Detailed usage can be found in the [updated README](https://github.com/DreaminginCodeZH/MaterialProgressBar#using-widget).

**Comment by AshkanImmortal** [comment] 2015-09-23 07:15
Hey, Thanks for great library, I will integrate soon.

**Comment by afollestad** [comment] 2015-09-23 14:54
@dreamingincodezh thanks, I'll definitely use that and include credits ☺

**Comment by afollestad** [comment] 2015-09-23 14:58
@AshkanImmortal his library is already being used, he just made it easier to use it
