### ISSUE TITLE
[Feature] - MaterialColorChooserPreference

### ISSUE THREAD

**Issue by vanniktech** [afollestad/material-dialogs#837] opened 2015-11-21 18:53 UTC
This preference would automatically save the selected color in the preferences and when clicked it should open the ColorChooserDialog

**Comment by afollestad** [comment] 2015-11-21 18:55
This is a duplicate of another issue. 

It can't be done with the current color chooser since it's a `DialogFragment`. It's easier to use a regular preference and listen for clicks.

**Comment by afollestad** [comment] 2015-11-21 18:56
Two of my apps do that, and I just use a custom view to indicate the currently selected color.

**Closed by afollestad** 2015-11-21 18:55 UTC
