### ISSUE TITLE
Error:(23, 13) Failed to resolve: com.afollestad:material-dialogs:0.7.2.4

### ISSUE THREAD

**Issue by Lomovskiy** [afollestad/material-dialogs#465] opened 2015-04-19 00:43 UTC
Hello. Help me, please. Gradle synс is failed.
Error:(23, 13) Failed to resolve: com.afollestad:material-dialogs:0.7.2.4

**Comment by afollestad** [comment] 2015-04-19 01:13
This is a duplicate of many other issues

**Closed by afollestad** 2015-04-19 01:13 UTC

**Comment by Lomovskiy** [comment] 2015-04-19 10:01
I use jcenter()
![default](https://cloud.githubusercontent.com/assets/3610603/7218993/04e8b39e-e694-11e4-8013-8916752d2140.PNG)
![default](https://cloud.githubusercontent.com/assets/3610603/7218997/1b7f3998-e694-11e4-9d61-b58906dd3575.PNG)
But problem remains...

**Comment by afollestad** [comment] 2015-04-21 00:02
If you haven't solved it yet, here's a work around. The jCenter repository went down yesterday so this is necessary right now regardless:

Add this inside repositories { }

```Gradle
maven { url 'https://dl.bintray.com/drummer-aidan/maven' }
```

**Comment by afollestad** [comment] 2015-04-23 14:41
The library is back on jCenter now
