### ISSUE TITLE
How to use it in java?

### ISSUE THREAD

**Issue by zhengzyty** [afollestad/material-dialogs#1993] opened 2020-05-15 09:20 UTC
*Please consider making a Pull Request if you are capable of doing so.*

**What module does this apply to?**

Core? Input? Files? Color?

**Description what you'd like to happen:**

A clear description if the feature or behavior you'd like implemented.

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

**Comment by zsxeee** [comment] 2020-05-30 08:04
Duplicate of #1864

**Comment by zsxeee** [comment] 2020-05-30 08:08
or use 0.9.6.0 if you need

**Comment by G00fY2** [comment] 2020-06-24 23:52
If you use simple dialogs and want to add them to legacy java classes you can also use something like that:
```kotlin
object MaterialDialogsHelper {

  @JvmStatic
  fun showDialog(
    context: Context,
    dialogTitle: String?,
    dialogMessage: String?,
    dialogPositive: String?,
    dialogNegative: String?,
    dialogCancelable: Boolean,
    dialogPositiveAction: DialogButtonAction?
  ): MaterialDialog {
    return MaterialDialog(context).show {
      dialogTitle?.let { title(text = it) }
      dialogMessage?.let { message(text = it) }
      dialogPositive?.let { positiveButton(text = it, click = { dialogPositiveAction?.onClick() }) }
      dialogNegative?.let { negativeButton(text = it) }
      cancelable(dialogCancelable)
    }
  }

  interface DialogButtonAction {
    fun onClick()
  }
}
```

**Closed** 2020-06-30 07:21 UTC
Labels: improvement
