### ISSUE TITLE
Could not find com.github.afollestad.material-dialogs:core:0.8.5.0.

### ISSUE THREAD

**Issue by alemedero** [afollestad/material-dialogs#818] opened 2015-11-09 16:34 UTC
Hi, i keep getting the following error when i add the library.

```Gradle
Error:Could not find com.github.afollestad.material-dialogs:core:0.8.5.0.
```

```Gradle
repositories {
    maven {
        url 'https://jitpack.io'
    }
    mavenCentral()
}
```

And added this as a dependency:

```Gradle
compile('com.github.afollestad.material-dialogs:core:0.8.5.0@aar') {
    transitive = true
}
```

**Comment by afollestad** [comment] 2015-11-09 16:38
This is a duplicate of closed issues, I'm sure. But there's not much I can do.

It's available on JitPack (https://jitpack.io/#com.afollestad/material-dialogs) and that's the correct repo information.

**Closed by afollestad** 2015-11-09 16:38 UTC

**Comment by nicolaschengdev** [comment] 2015-11-13 12:41
Hi,

you mentioned the correct repo information here 
https://jitpack.io/#com.afollestad/material-dialogs/0.8.5.0

But it gives error below 

Error:Could not find material-dialogs.aar (com.afollestad:material-dialogs:0.8.5.0).
Searched in the following locations:
    https://jitpack.io/com/afollestad/material-dialogs/0.8.5.0/material-dialogs-0.8.5.0.aar

Did someone manage to add the library ?

**Comment by longxianlin** [comment] 2015-11-20 10:31
same question.

**Comment by svenjacobs** [comment] 2015-12-02 13:44
It seems like 0.8.5.0 is missing from Jitpack? Opening `https://jitpack.io/com/afollestad/material-dialogs/core/0.8.5.0/` results in 404 for instance.

**Comment by afollestad** [comment] 2015-12-02 14:35
Builds can't be removed completely from.JitPack, if you request it from Gradle it will be built again if it was removed.

**Comment by afollestad** [comment] 2015-12-02 15:27
Also, you should use `https://jitpack.io/afollestad/material-dialogs/core/0.8.5.0` instead

**Comment by afollestad** [comment] 2015-12-04 00:43
Anyone still having issues, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.

**Comment by roshaplus** [comment] 2017-12-03 23:05
compile 'com.afollestad.material-dialogs:core:0.9.6.0'

**Comment by roshaplus** [comment] 2017-12-03 23:10
compile 'com.afollestad.material-dialogs:core:0.8.6.1'
    compile 'com.afollestad.material-dialogs:commons:0.8.6.1'
