### ISSUE TITLE
add support for android support library 23.2.0

### ISSUE THREAD

**Issue by a642500** [afollestad/material-dialogs#962] opened 2016-02-25 03:13 UTC
After update to [support library 23.2.0](http://android-developers.blogspot.com/2016/02/android-support-library-232.html),  a error occurs when aapt
```
Error:(3, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').
```
on file:
```
\path\to\my\project\app\build\intermediates\exploded-aar\com.github.afollestad.material-dialogs\core\0.8.5.4\res\values-v11\values-v11.xml
```

There may be some other resources which are removed from support 23.2.0. 
Please update and be compatible with this new released support library.
Thanks.

By the way, this release also add the ``Theme.AppCompat.DayNight```. This allows apps to easily support both a Light and Dark theme. I hope you can add support it in later release, too.

**Comment by afollestad** [comment] 2016-02-25 03:19
Duplicate of two issues opened within the past two hours.

**Closed by afollestad** 2016-02-25 03:19 UTC

**Comment by afollestad** [comment] 2016-02-25 05:00
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.5

**Comment by afollestad** [comment] 2016-02-25 05:07
The above won't work until JitPack installs version 23.2.0 of the Google libs repo.
