### ISSUE TITLE
Dialog shakes when selecting the last item of a long single choice ListView

### ISSUE THREAD

**Issue by esdras-gb** [afollestad/material-dialogs#175] opened 2015-01-09 01:54 UTC
Hi, I'm facing a issue with MaterialDialog (latest version) , I will explain my scenario. I Have the following code (inside a fragment):
``` 

private void show(){
    MaterialDialog dialog = new MaterialDialog.Builder(getActivity())
                    .title(R.string.app_name)
                    .items(arr)
                    .positiveText(R.string.next)
                    .cancelable(false)
                    .itemsCallbackSingleChoice(-1, new MaterialDialog.ListCallback() {
                        @Override
                        public void onSelection(MaterialDialog materialDialog, View view, int i, CharSequence charSequence) {
                        }
                    })
                    .build();

    dialog.show();
}
```

where arr is a array of String with 10 items. When I scroll down the list view and touch the last element, my listview shakes and the last element is half hidden by positive view, other times my listview shakes until I scroll up. I try it at my device (Nexus 4 Lollipop) and  at emulator (Genymotion, Android 4.3) and the result was the same. I made a small video to show it.

http://youtu.be/Axr9uHZi2BQ (Genymotion)

http://youtu.be/TqC_rvhJo_E (Nexus 4 Lollipop)

I figured out when I'm trying put a edittext inside at footerview. The result was the same. At first a thought was a problem to display the soft keyboard, so I decide remove the footerview and check if it was still happening. Then I realized that it occurs when I have a long options list 

I appreciate any help

Thanks

**Comment by teslacoil** [comment] 2015-01-09 03:38
I only took a quick look, but I think canAdapterViewScroll is getting fooled by being at the bottom of the list, and we must be invalidateCustomViewAssociations after an item is selected. I'll take a more indepth look tonight or tomorrow, should be a quick fix if I'm right.

**Comment by hzsweers** [comment] 2015-01-09 03:54
@teslacoil I don't think it's that simple. In my testing, the window will wiggle even if no item's been selected.

**Comment by afollestad** [comment] 2015-01-10 00:43
@teslacoil @hzsweers once this is repaired, I'll push 0.6.0

**Comment by teslacoil** [comment] 2015-01-10 01:59
@hzsweers I couldn't directly reproduce, but could reproduce a single vibration when scrolled to the bottom and selecting an item (or doing anything to cause invalidateCustomViewAssociations).
I've pushed a fix to my fork for what I saw, which I suspect will fix the issue you're seeing also but it'd be great if you could confirm.

https://github.com/teslacoil/material-dialogs

Specifically https://github.com/teslacoil/material-dialogs/commit/37cd212aae30739cf257dee5413f341602c3cb23

I'll wait to submit a pull request in case it's not a complete fix.

**Comment by hzsweers** [comment] 2015-01-10 02:08
@teslacoil I'll take a look this later evening

**Comment by hzsweers** [comment] 2015-01-10 06:02
@teslacoil @afollestad that looks like it fixed it!

**Comment by afollestad** [comment] 2015-01-10 17:45
Release 0.6.0 is now available

**Closed** 2015-01-10 17:49 UTC
Labels: bug
