### ISSUE TITLE
Stacked Buttons are always on center – Gravity not set on newer API levels

### ISSUE THREAD

**Issue by TomasValenta** [afollestad/material-dialogs#256] opened 2015-02-16 10:03 UTC
Sorry Aidan,
is the same issue like #234, but I cannot fix it. I have tested many situation, but when **forceStacking is true**, the buttons are **always in middle**.

![Screen](http://www.yetanotherview.cz/tmp/screen-button-stacked.png)

Using .btnStackedGravity(GravityEnum.anything) does not help. The problem started with version **0.6.2.2** and remains to **0.6.3.0**, with **0.6.2.1** everything works fine.
Have you any idea where may be a problem?

**Comment by TomasValenta** [comment] 2015-02-16 18:37
I found an interesting thing. When i'm trying it in emulator with different apis, the result is different:
on API 17 and 21 is the result same = align is center.
but
on API 15 is correct:

![Screen](http://www.yetanotherview.cz/tmp/screen-button-stacked-ok.png)

**Comment by afollestad** [comment] 2015-02-16 19:07
Hmmm, I'm not able to reproduce this issue on API 17 or 21

**Comment by afollestad** [comment] 2015-02-16 19:09
Not on API 16 either

**Comment by afollestad** [comment] 2015-02-16 19:09
Not on API 16. I only use API 21 with physical devices (my old Nexus 5 and my Nexus 6). I tested API 16, 17, and 19 with emulators and it works fine.

**Comment by TomasValenta** [comment] 2015-02-16 20:36
Ok,
I tried now create blank new project only with stacked dialog:

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        showStacked();
    }

    private void showStacked() {
        new MaterialDialog.Builder(this)
                .title(R.string.useGoogleLocationServices)
                .content(R.string.useGoogleLocationServicesPrompt)
                .positiveText(R.string.speedBoost)
                .negativeText(R.string.noThanks)
                .forceStacking(true)  // this generally should not be forced
                .show();
    }
```

and this is the result on API 21 (Real and also in Emulator):

![Screen](http://www.yetanotherview.cz/tmp/screen-button-stacked-test.png)

You can [download it here.](http://www.yetanotherview.cz/tmp/Test.zip)

**Comment by afollestad** [comment] 2015-02-16 20:48
If I force stacking in Cabinet (which uses the Gradle dependency), the result is this on Lollipop:

![rsz_mdstacked](https://cloud.githubusercontent.com/assets/1820165/6219080/e519d1c6-b5ea-11e4-9858-069228941cc6.png)

**Comment by TomasValenta** [comment] 2015-02-16 20:53
I do not understand it :) Have you tried the simple project, that i have added above?

**Comment by afollestad** [comment] 2015-02-16 20:59
Hmm, weird, it happens with that test project.

@hzsweers any idea why this would happen? It works fine in my apps but not in new projects.

**Comment by hzsweers** [comment] 2015-02-16 21:34
I have no idea. When you or @TomasValenta press the button, does the ripple just wrap the text or does it match the width of the dialog (as in, maybe a layout gravity issue). Alternatively, does changing the order of the method calls in the builder change anything?

**Comment by TomasValenta** [comment] 2015-02-17 09:52
@hzsweers: The ripple wrap the whole width of the dialog. Changing order of the method calls in the builder does not change anything of the situation, but I have not tried all combinations...

**Comment by hzsweers** [comment] 2015-02-17 11:35
Idk then

**Comment by afollestad** [comment] 2015-02-17 19:53
This is very weird.

**Comment by athornz** [comment] 2015-02-19 21:41
I'm also getting this issue - tested on lollipop and 4.4.4

**Comment by athornz** [comment] 2015-02-19 21:57
The stacked buttons are match the parent width with a gravity of center - should the gravity be left? Or should the buttons wrap content?

**Comment by afollestad** [comment] 2015-02-19 21:58
The gravity and/or text alignment is set in the code, not the layout.

They have to be match parent so the entire span of the dialog is clickable where they are.

**Comment by athornz** [comment] 2015-02-19 22:01
I can see it set in the xml style. Changing it in the style fixes the gravity.

**Comment by afollestad** [comment] 2015-02-19 22:05
Really? It shouldn't, since they are overrided at runtime from MaterialDialog.java

**Comment by athornz** [comment] 2015-02-19 22:06
Hmm I can see it being set in code as well. Let me do some debugging.

**Comment by afollestad** [comment] 2015-02-19 22:09
Oh wait! I think I know why!

Gravity is only used on certain API levels, text alignment is used on API levels where it's supported (newer ones). Thus the gravity is messed up on newer Android versions because gravity is actually not reset when text alignment is.

**Comment by afollestad** [comment] 2015-02-19 22:09
So removing it from styles would indeed be a valid fix, so there's no default value.

**Comment by athornz** [comment] 2015-02-19 22:19
Removing the gravity removes the centered text, but it seems text alignment is having no effect. The text is now aligned left :(

**Comment by afollestad** [comment] 2015-02-19 22:20
So it would probably be better to remove text alignment altogether and just use gravity. Using text alignment was added via a pull request quite a while ago, I thought it had worked back then oddly enough.

**Comment by athornz** [comment] 2015-02-19 22:23
Hmm. Text alignment would definitely be good if it actually worked.

**Comment by athornz** [comment] 2015-02-19 22:45
Actually I don't know why text alignment would be any better. Gravity can be set to start and end, so that will work for RTL layouts

**Comment by afollestad** [comment] 2015-02-19 22:46
Text alignment does too, it's a newer API so there's no way it wouldn't (RTL support came with Jellybean).

See https://github.com/afollestad/material-dialogs/blob/master/library/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L344

**Comment by athornz** [comment] 2015-02-19 22:48
Yea. I think it may have bugs. I debugged it and setTextAlignment checks if the new alignment is different the 'raw alignment', which is always false. Although I'm not sure why - its a bit beyond me.

**Comment by afollestad** [comment] 2015-02-19 22:55
This should hopefully be fixed now with the latest commits. It won't go live as a release until it's tested a bit more.

**Closed by afollestad** 2015-02-19 22:55 UTC
Labels: bug, help wanted

**Comment by afollestad** [comment] 2015-02-19 23:14
https://github.com/afollestad/material-dialogs/releases/tag/0.6.3.1
