### ISSUE TITLE
SpannableString Usage in List

### ISSUE THREAD

**Issue by easycheese** [afollestad/material-dialogs#1873] opened 2019-09-02 20:59 UTC
I'm converting an app to utilize this library and running into a problem. The old list uses SpannableString in a single selection dialog (it has a Badge on 'Premium' options to indicate). Is there really no way to use SpannableStrings with this library?

**Comment by afollestad** [comment] 2019-09-02 22:34
Effectively a duplicate of https://github.com/afollestad/material-dialogs/issues/1867 and resolved by an open PR

**Closed by afollestad** 2019-09-02 22:34 UTC
Labels: bug
