### ISSUE TITLE
Ability to change button selectors

### ISSUE THREAD

**Issue by milek** [afollestad/material-dialogs#177] opened 2015-01-09 11:28 UTC
Changing background of buttons when there are more than 1 reverts background back to default.

Example 
```java
MaterialDialog dialog = new MaterialDialog.Builder(getActivity())
        .title(R.string.fill_submit_title)
        .content(R.string.fill_submit_content)
        .positiveColorRes(android.R.color.white)
        .positiveText("Yes")
        .negativeColorRes(R.color.form_default_dark)
        .negativeText("No")
        .autoDismiss(true)
        .callback(callback)
        .build();

View okButton = dialog.getActionButton(DialogAction.POSITIVE);
okButton.setBackgroundResource(R.drawable.base_button_blue);

dialog.show();
```

But this example works perfectly fine:
```java
MaterialDialog dialog = new MaterialDialog.Builder(getActivity())
        .title(title).content(content)
        .positiveColorRes(R.color.main_color)
        .positiveText("Done").autoDismiss(true)
        .build();

View okButton = dialog.getActionButton(DialogAction.POSITIVE);
okButton.setBackgroundResource(R.drawable.base_button_blue);

dialog.show();
```

**Comment by afollestad** [comment] 2015-01-09 14:59
This is not a bug, just the design. The selectors are changed via code based on the theme.

**Comment by milek** [comment] 2015-01-09 15:20
Right, but with only one button I can change the background and it stays, but with more than one button it reverts back. So one of the functionalities contains a bug.

Personally I would love to have an ability to modify the background of the button. One of the requirement in project I have, is that positive button have primary color as a background and not text foreground.

**Comment by afollestad** [comment] 2015-01-09 18:49
Well setting a static color to a button would be a bad idea, that would disable the selector states. 

I'll add selector theming capabiltiies in the next release.

**Comment by afollestad** [comment] 2015-01-09 18:56
Wait, I was thinking since I just woke up. But you can already change the color of the buttons. You can use `accentColor` or `accentColorRes` of the `Builder`, which in turn calls `positiveColor`, `negativeColor`, and `neutralColor`. You can also set the `colorAccent` AppCompat attribute or `android:colorAccent` Material theme attribute. You can even use the `ThemeSingleton` class and set the accent color at anytime globally through your app.

@milek

**Comment by afollestad** [comment] 2015-01-09 19:23
This will be in the next release. Note that you will want to copy the default selectors, with their insets and padding, into your custom one. Otherwise they will not work correctly.

**Closed by afollestad** 2015-01-09 19:23 UTC

**Comment by milek** [comment] 2015-01-10 13:23
Awesome, thanks!
