### ISSUE TITLE
Unable to update gradle dependency for the library

### ISSUE THREAD

**Issue by jimmy201516** [afollestad/material-dialogs#830] opened 2015-11-18 03:09 UTC
hi,i am trying to use the library and config the gradle as fellow:
project gradle:
buildscript {
    repositories {
        jcenter()
    }
    dependencies{
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()        
        maven { url "https://jitpack.io" }  //and try move it to app grade but problem as the same
    }
}

app gradle:
apply plugin: 'com.android.library'

android {
    compileSdkVersion 22
    buildToolsVersion '22.0.1'
    defaultConfig {
        minSdkVersion 10
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    repositories {
        //maven { url "https://jitpack.io" }
        flatDir{ dirs 'libs'}
    }
}

dependencies {
    compile('com.github.afollestad.material-dialogs:core:0.8.5.1@aar') {
        transitive = true
    }
    //compile('com.github.afollestad.material-dialogs:commons:0.8.5.1@aar') {
    //    transitive = true
    //}    
}

where is the problem?

error: could not resolve com.github.afollestad.material-dialogs:core:0.8.5.1

**Comment by afollestad** [comment] 2015-11-18 03:10
This is a duplicate of many issues.

**Comment by afollestad** [comment] 2015-11-18 03:11
It should always go in your module `build.gradle` file though.

**Closed by afollestad** 2015-11-18 03:10 UTC

**Comment by jimmy201516** [comment] 2015-11-18 03:31
would you give me a aar file download url? thank you!

**Comment by afollestad** [comment] 2015-12-04 00:42
Anyone still having issues, see this response from JitPack: https://github.com/jitpack/jitpack.io/issues/318

I will be updating the project REAMDE also.

**Comment by afollestad** [comment] 2015-12-18 19:13
https://github.com/afollestad/material-dialogs/releases/tag/0.8.5.3

**Comment by afollestad** [comment] 2016-05-13 21:18
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
