### ISSUE TITLE
Multi choice large list checked state issue

### ISSUE THREAD

**Issue by FrancisCan** [afollestad/material-dialogs#154] opened 2015-01-02 19:04 UTC
Hi I noticed that using many items in  multi choice dialog, due to of recycle of views, items that aren't checked by the user seem checked, instead the callback works great.

**Comment by afollestad** [comment] 2015-01-02 22:25
Hmmm. I haven't run into this issue. Can you clarify?

**Comment by FrancisCan** [comment] 2015-01-02 22:48
Yes.. I have a list of 30 items .. I check only the first item, but scrolling the list, also elements 10 , 19 , 28 are apparently checked. But the callback get only the first item and this is correct. I believe is the recycle of view that cause this error.

**Comment by afollestad** [comment] 2015-01-02 22:51
Hmmm, that shouldn't be a recycling issue. The checked states get reset every time: https://github.com/afollestad/material-dialogs/blob/master/library/src/main/java/com/afollestad/materialdialogs/MaterialDialog.java#L1481

Any ideas @hzsweers? (he made a pull request recently that redesigned this system)

**Comment by hzsweers** [comment] 2015-01-03 10:25
I'll look into it

**Comment by hzsweers** [comment] 2015-01-03 13:53
@FrancisCan I'm unable to reproduce this with this snippet:

```java
CharSequence[] items = new CharSequence[30];
for (int i = 0; i < items.length; ++i) {
    items[i] = "" + i;
}
new MaterialDialog.Builder(this)
        .title(R.string.socialNetworks)
        .items(items)
        .itemsCallbackMultiChoice(new Integer[]{1, 3}, new MaterialDialog.ListCallbackMulti() {
            @Override
            public void onSelection(MaterialDialog dialog, Integer[] which, CharSequence[] text) {
                StringBuilder str = new StringBuilder();
                for (int i = 0; i < which.length; i++) {
                    str.append(which[i]);
                    str.append(": ");
                    str.append(text[i]);
                    str.append('\n');
                }
                Toast.makeText(getApplicationContext(), str.toString(), Toast.LENGTH_LONG).show();
            }
        })
        .positiveText(R.string.choose)

        .show();
```

Could you maybe provide an example code snippet that displays this behavior?

**Comment by FrancisCan** [comment] 2015-01-03 14:08
@hzsweers My code is the same! The only difference is 

```
  .itemsCallbackMultiChoice(null , new MaterialDialog.ListCallbackMulti() 
```
( like @afollestad wrote in the README at this line https://github.com/afollestad/material-dialogs#multi-choice-list-dialogs )

instead of 
```java
.itemsCallbackMultiChoice(new Integer[]{1, 3}, new MaterialDialog.ListCallbackMulti() 
```

If I use:
```java
.itemsCallbackMultiChoice(new Integer[]{}, new MaterialDialog.ListCallbackMulti() 
```
it works.

**Comment by afollestad** [comment] 2015-01-03 19:28
@FrancisCan this is now fixed via a pull request from @hzsweers. The next release will include this fix.

**Closed by afollestad** 2015-01-03 19:28 UTC
Labels: bug

**Comment by afollestad** [comment] 2015-01-04 00:32
Release 0.5.4 is now available @FrancisCan
