### ISSUE TITLE
Build Errors: Error retrieving parent for Item

### ISSUE THREAD

**Issue by mxjones** [afollestad/material-dialogs#717] opened 2015-09-24 13:35 UTC
Getting a build error when attempting to use this library:

\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\23.0.1\res\values-v23\values-v23.xml

Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.

**Comment by afollestad** [comment] 2015-09-24 13:50
This is a duplicate of another closed issue. 

Update build tools in your app, along with all the Google libs in the SDK Manager.

**Closed by afollestad** 2015-09-24 13:50 UTC

**Comment by mxjones** [comment] 2015-09-24 19:38
Hi, thanks for the quick reply. I didn't see those issue but my my libraries are up to date;
Build tools/Support Library at latest version 23.0.1, SDK tools at latest version 24.3.4.

Currently using https://developer.android.com/reference/android/support/v7/app/AlertDialog.html as I have a fairly simple requirement right now.

Cheers

**Comment by afollestad** [comment] 2015-09-24 19:49
You're targeting SDK 23, too?

Otherwise there's not much I can do.

**Comment by afollestad** [comment] 2015-09-24 19:50
https://github.com/afollestad/material-dialogs/issues/684

**Comment by mxjones** [comment] 2015-09-26 20:45
Hi,

This was caused by a separate shared module I included in my android project, the module was targeting an older build tools version in the gradle file. Updating the build tools version, and corresponding support libraries to 23.0.1 resolved the issue.

Cheers!
