### ISSUE TITLE
Dialog on rotation

### ISSUE THREAD

**Issue by Pirksy** [afollestad/material-dialogs#645] opened 2015-08-07 10:51 UTC
AlertDialogWrapper disappears while rotation, how can I fix it?

**Comment by afollestad** [comment] 2015-08-07 13:49
Duplicate of many issues

**Closed by afollestad** 2015-08-07 13:49 UTC

**Comment by Rainer-Lang** [comment] 2015-08-07 16:25
@Pirksy Often asked. Look at "DialogFragment".
