### ISSUE TITLE
Failed to resolve: com.afollestad:material-dialogs:0.6.3.0

### ISSUE THREAD

**Issue by marchinram** [afollestad/material-dialogs#504] opened 2015-05-05 22:02 UTC
I get the following error, I tried following some steps posted in closed issues with no success:

Error:(148, 13) Failed to resolve: com.afollestad:material-dialogs:0.6.3.0
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

I'm on Android Studio 1.2, my repositories for my module gradle file is:

    repositories {
        flatDir {
            dirs 'libs'
        }
        mavenCentral()
        maven
        {
            url { "https://github.com/bitstadium/HockeySDK-Android" }
        }
    }

Any ideas what I need to do to fix this.  As recently as yesterday it was building fine not sure what has happened.

**Comment by afollestad** [comment] 2015-05-05 22:02
This is the 5th or 6th duplicate of the same issue.

Read the README file.

**Comment by afollestad** [comment] 2015-05-05 22:03
0.7.3.1 is the current version btw

**Closed by afollestad** 2015-05-05 22:02 UTC

**Comment by afollestad** [comment] 2016-05-13 21:20
The library is now on jCenter, as an alternative to JitPack.io. jCenter is Android Studio's default Maven repository.

See the README for updated dependency info: https://github.com/afollestad/material-dialogs#gradle-dependency
