### ISSUE TITLE
List dialog (radio) colors don't change back after selection

### ISSUE THREAD

**Issue by TheAndroidMaster** [afollestad/material-dialogs#605] opened 2015-07-04 19:54 UTC
When the dialog is first brought up, all the radio buttons are gray and unselected. I used my own code to keep the radio selected when the dialog is brought up again, that code is below. Upon selection, they change color. But when another option is selected, the first option stays the same color. Only some of them do this, and I haven't yet found a pattern to it. There are a lot of public voids called, these do not affect the dialogs, only the titles of the buttons.

Code for the dialogs:

```java
        Button home = (Button) findViewById(R.id.button);
        Button work = (Button) findViewById(R.id.button2);
        Button everywhere = (Button) findViewById(R.id.button3);

        home.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new MaterialDialog.Builder(Preferences.this)
                        .title("Home Settings")
                        .items(R.array.ringtone)
                        .itemsCallbackSingleChoice(selecth, new MaterialDialog.ListCallbackSingleChoice() {
                            @Override
                            public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                                if (which == 0) {
                                    Double d = 1.0;
                                    Prefs.putDouble("homenum", d);
                                    selecth = 0;
                                    Prefs.putInt("selecth", selecth);
                                }
                                if (which == 1) {
                                    Double d = 2.0;
                                    Prefs.putDouble("homenum", d);
                                    selecth = 1;
                                    Prefs.putInt("selecth", selecth);
                                }
                                if (which == 2) {
                                    Double d = 3.0;
                                    Prefs.putDouble("homenum", d);
                                    selecth = 2;
                                    Prefs.putInt("selecth", selecth);
                                }
                                if (which == 3) {
                                    Double d = 4.0;
                                    Prefs.putDouble("homenum", d);
                                    selecth = 3;
                                    Prefs.putInt("selecth", selecth);
                                }
                                if (which == 4) {
                                    Double d = 5.0;
                                    Prefs.putDouble("homenum", d);
                                    selecth = 4;
                                    Prefs.putInt("selecth", selecth);
                                }
                                if (which == 5) {
                                    Double d = 6.0;
                                    Prefs.putDouble("homenum", d);
                                    selecth = 5;
                                    Prefs.putInt("selecth", selecth);
                                }
                                return true;
                            }
                        })
                        .positiveText("Save")
                        .neutralText("Set home location...")
                        .callback(new MaterialDialog.ButtonCallback() {
                            @Override
                            public void onPositive(MaterialDialog dialog) {
                                dialog.hide();
                            }

                            @Override
                            public void onNeutral(MaterialDialog dialog) {
                                //for button.setText
                                selectedDialog = "home";
                                getMapsResult();
                                savePlace();
                            }
                        })
                        .autoDismiss(false)
                        .show();
            }
        });

        work.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new MaterialDialog.Builder(Preferences.this)
                        .title("Work Settings")
                        .items(R.array.ringtone)
                        .itemsCallbackSingleChoice(selectw, new MaterialDialog.ListCallbackSingleChoice() {
                            @Override
                            public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                                if (which == 0) {
                                    Double d = 1.0;
                                    Prefs.putDouble("worknum", d);
                                    selectw = 0;
                                    Prefs.putInt("selectw", selectw);
                                }
                                if (which == 1) {
                                    Double d = 2.0;
                                    Prefs.putDouble("worknum", d);
                                    selectw = 1;
                                    Prefs.putInt("selectw", selectw);
                                }
                                if (which == 2) {
                                    Double d = 3.0;
                                    Prefs.putDouble("worknum", d);
                                    selectw = 2;
                                    Prefs.putInt("selectw", selectw);
                                }
                                if (which == 3) {
                                    Double d = 4.0;
                                    Prefs.putDouble("worknum", d);
                                    selectw = 3;
                                    Prefs.putInt("selectw", selectw);
                                }
                                if (which == 4) {
                                    Double d = 5.0;
                                    Prefs.putDouble("worknum", d);
                                    selectw = 4;
                                    Prefs.putInt("selectw", selectw);
                                }
                                if (which == 5) {
                                    Double d = 6.0;
                                    Prefs.putDouble("worknum", d);
                                    selectw = 5;
                                    Prefs.putInt("selectw", selectw);
                                }
                                return true;
                            }
                        })
                        .positiveText("Save")
                        .neutralText("Set work location...")
                        .callback(new MaterialDialog.ButtonCallback() {
                            @Override
                            public void onPositive(MaterialDialog dialog) {
                                dialog.hide();
                            }

                            @Override
                            public void onNeutral(MaterialDialog dialog) {
                                //for button.setText
                                selectedDialog = "work";
                                getMapsResult();
                                savePlace();
                            }
                        })

                        .autoDismiss(false)
                        .show();

            }
        });

        everywhere.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new MaterialDialog.Builder(Preferences.this)
                        .title("Normal Ringtone")
                        .items(R.array.ringtone)
                        .itemsCallbackSingleChoice(selecte, new MaterialDialog.ListCallbackSingleChoice() {
                            @Override
                            public boolean onSelection(MaterialDialog dialog, View view, int which, CharSequence text) {
                                String pop = "else";
                                if (which == 0) {
                                    Double d = 1.0;
                                    selected(pop, d);
                                    selecte = 0;
                                    Prefs.putInt("selecte", selecte);
                                }
                                if (which == 1) {
                                    Double d = 2.0;
                                    selected(pop, d);
                                    selecte = 1;
                                    Prefs.putInt("selecte", selecte);
                                }
                                if (which == 2) {
                                    Double d = 3.0;
                                    selected(pop, d);
                                    selecte = 2;
                                    Prefs.putInt("selecte", selecte);
                                }
                                if (which == 3) {
                                    Double d = 4.0;
                                    selected(pop, d);
                                    selecte = 3;
                                    Prefs.putInt("selecte", selecte);
                                }
                                if (which == 4) {
                                    Double d = 5.0;
                                    selected(pop, d);
                                    selecte = 4;
                                    Prefs.putInt("selecte", selecte);
                                }
                                if (which == 5) {
                                    Double d = 6.0;
                                    selected(pop, d);
                                    selecte = 5;
                                    Prefs.putInt("selecte", selecte);
                                }
                                return true;
                            }
                        })
                        .positiveText("Save")
                        .callback(new MaterialDialog.ButtonCallback() {
                            @Override
                            public void onPositive(MaterialDialog dialog) {
                                dialog.hide();
                            }
                        })

                        .autoDismiss(false)
                        .show();
            }
        });


onCreate code:

        new Prefs.Builder()
                .setContext(this)
                .setMode(ContextWrapper.MODE_PRIVATE)
                .setPrefsName(getPackageName())
                .setUseDefaultSharedPreference(true)
                .build();

        //the strings
        hom = Prefs.getString("home", "");
        wok = Prefs.getString("work", "");
        elsestr = Prefs.getString("elsestr", "");
        //the numbers
        els = Prefs.getDouble("else", 0);
        homnum = Prefs.getDouble("homenum", 0);
        woknum = Prefs.getDouble("worknum", 0);
        //the locations
        locateh = Prefs.getString("coordh", "");
        locatew = Prefs.getString("coordw", "");

        selecth = Prefs.getInt("selecth", -1);
        selectw = Prefs.getInt("selectw", -1);
        selecte = Prefs.getInt("selecte", -1);
        selects = Prefs.getInt("selects", -1);
        selectv = Prefs.getInt("selectv", -1);
        selectq = Prefs.getInt("selectq", -1);
        selectm = Prefs.getInt("selectm", -1);
        selectl = Prefs.getInt("selectl", -1);

        Button home = (Button) findViewById(R.id.button);
        Button work = (Button) findViewById(R.id.button2);
        Button everywhere = (Button) findViewById(R.id.button3);
        Button silent = (Button) findViewById(R.id.button4);
        Button vibrate = (Button) findViewById(R.id.button5);
        Button quiet = (Button) findViewById(R.id.button6);
        Button mid = (Button) findViewById(R.id.button7);
        Button loud = (Button) findViewById(R.id.button8);

        home.setText(home.getText() + " " + hom);
        work.setText(work.getText() + " " + wok);
        everywhere.setText(everywhere.getText() + " " + elsestr);
```

**Comment by afollestad** [comment] 2015-07-05 19:58
Updated your comment to use syntax highlighting. Indentation doesn't do that.

I'll look at this when I have a bit more time.

**Comment by afollestad** [comment] 2015-07-13 01:43
This appears to be a duplicate of https://github.com/afollestad/material-dialogs/issues/564.

**Closed by afollestad** 2015-07-13 01:43 UTC
Labels: possible bug
