### ISSUE TITLE
Horizontal Indeterminate Progress not showing pre-21

### ISSUE THREAD

**Issue by Gerlot** [afollestad/material-dialogs#664] opened 2015-08-28 09:52 UTC
Hi,
I'm using your lib on a project with a minimum sdk level 14 (ICS) and I noticed that the horizontal version of the indeterminate progress is not showing on pre-21 devices. On API21 and later it's fine, but even on KitKat it's nowhere to be found.

I created the dialog according to the README (only difference is, that I didn't use a content, but it isn't showing when I set a content text either):

```java
new MaterialDialog.Builder(this)
    .title(R.string.progress_dialog)
    .progress(true, 0)
    .progressIndeterminateStyle(true)
    .show();
```

**Comment by afollestad** [comment] 2015-08-29 00:03
Duplicate of https://github.com/afollestad/material-dialogs/issues/636

**Closed by afollestad** 2015-08-29 00:03 UTC
Labels: duplicate

**Comment by afollestad** [comment] 2015-09-17 20:36
https://github.com/afollestad/material-dialogs/releases/tag/0.8.0.0

**Comment by afollestad** [comment] 2015-09-23 21:38
https://github.com/afollestad/material-dialogs/releases/tag/0.8.1.0
