### ISSUE TITLE
How to do not dismiss dialog when i pressed the back button?

### ISSUE THREAD

**Issue by Jack1995** [afollestad/material-dialogs#1537] opened 2018-04-03 02:25 UTC
(`[x]` becomes a filled in checkbox, `[ ]` is an empty one)

- [ ] *I understand that dialogs which require a combination of different dialog types provided by this library (e.g. list + progress, input + checkbox) require a **custom view**.*
- [ ] I have verified there are [no duplicate active or recent bugs, questions, or requests](https://github.com/afollestad/material-dialogs/issues?q=is%3Aissue+is%3Aclosed)
- [ ] I have verified that I am using the latest version of Material Dialogs.
- [ ] I have given my issue a non-generic title.
- [ ] I have [read over the documentation](https://github.com/afollestad/material-dialogs/blob/master/README.md) (before asking questions on how to do something).

---

###### Include the following:
 - Material Dialogs version: `0.x.x.x`
 - Device OS version: `7.1.1`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel XL`

Also, please wrap your code with correct syntax highlighting.

```java
System.out.println("Hello, world!");
```

```xml
<LinearLayout ...></LinearLayout>
```
 
---
 
###### Reproduction Steps

1. 
2. 
3. 

---

###### Expected Result

---

**Comment by afollestad** [comment] 2018-04-03 02:25
This is a duplicate of countless issues.

**Closed by afollestad** 2018-04-03 02:25 UTC
