### ISSUE TITLE
Can't paste into EditText when it's empty - OnePlus devices

### ISSUE THREAD

**Issue by MatteCarra** [afollestad/material-dialogs#1826] opened 2019-07-01 08:46 UTC
**Library Version:**
2.0 -> 3.0.2
 
**Affected Device(s):**
 OnePlus 6 Android 9
 
**Describe the Bug:**
When I long press an empty MaterialDialog input (edittext), the Paste button is not shown.

**To Reproduce:**
```
        MaterialDialog(this).show {
            title(R.string.title)
            message(R.string.message)
            input(hintRes = R.string.hint)
            positiveButton(android.R.string.ok)
            negativeButton(android.R.string.cancel)
        }
```
Try to long press on the EditText to paste something in the clipboard.
This happens only when the text is empty. If a type a char and retry it pops up.
**Expected Behavior:**

It should popup the Paste option.

**Comment by afollestad** [comment] 2019-07-01 17:27
Unable to reproduce on my Pixel 3 XL. I suspect this could be an OS issue on OnePlus.

**Comment by MatteCarra** [comment] 2019-07-01 17:35
Thanks for the confirmation.
I just tested it on an other device and the problem did not occur.
I have never had this before though.
I will do more tests, and if I come up with something I will create a pull request.

Thanks.

**Comment by sslp** [comment] 2019-07-03 22:18
Same issue on OnePlus 5.

**Comment by afollestad** [comment] 2019-07-11 17:08
Closing since this is out of my control.

**Closed by afollestad** 2019-07-11 17:08 UTC
Labels: can't reproduce
