### ISSUE TITLE
dialogWrapContent is not working?

### ISSUE THREAD

**Issue by zhuyonghao** [afollestad/material-dialogs#1983] opened 2020-04-25 07:36 UTC
Material Dialogs version: 3.3.0
API: 29
Device Manufacturer: Android
Device Name: Nexus 7 / Android Emulator

**Comment by afollestad** [comment] 2020-04-25 19:40
There isn't enough information here. What isn't working about it? What does it look like? How is your layout structured?

**Comment by afollestad** [comment] 2020-04-25 19:41
Actually, this is probably a duplicate of https://github.com/afollestad/material-dialogs/issues/1853, as well.

**Closed by afollestad** 2020-04-25 19:41 UTC
